# Generated by Django 4.1.7 on 2023-07-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_socialmedia_delete_socialmedias'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='photo',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
